// ============================================================
// Config — .env generation and docker-compose.yml patching
// ============================================================

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { PROVIDERS } from './constants.mjs';

function generateToken() {
  return crypto.randomBytes(32).toString('base64url');
}

export function generateEnvContent(config) {
  const providerInfo = PROVIDERS[config.provider];
  const lines = [
    '# ═══════════════════════════════════════════════════════════',
    '# Lancelot Configuration — Generated by create-lancelot',
    `# Generated: ${new Date().toISOString()}`,
    '# ═══════════════════════════════════════════════════════════',
    '',
    '# LLM Provider',
    `LANCELOT_PROVIDER=${config.provider}`,
  ];

  // OAuth mode: write auth mode instead of API key
  if (config.authMode === 'oauth') {
    lines.push('LANCELOT_AUTH_MODE=OAUTH');
    lines.push(`# ${providerInfo.envVar} not needed — using OAuth`);
  } else {
    lines.push(`${providerInfo.envVar}=${config.apiKey}`);
  }

  // Generate security tokens — store API token in config for OAuth flow
  const ownerToken = generateToken();
  const apiToken = generateToken();
  const vaultKey = generateToken();
  config._generatedApiToken = apiToken;

  lines.push(
    '',
    '# Security Tokens (auto-generated — keep secret)',
    `LANCELOT_OWNER_TOKEN=${ownerToken}`,
    `LANCELOT_API_TOKEN=${apiToken}`,
    `LANCELOT_VAULT_KEY=${vaultKey}`,
    '',
    '# Logging',
    'LANCELOT_LOG_LEVEL=INFO',
    '',
    '# Local Model',
    `LOCAL_MODEL_GPU_LAYERS=${config.gpuLayers || 0}`,
    '',
    '# Feature Flags',
    'FEATURE_SOUL=true',
    'FEATURE_SKILLS=true',
    'FEATURE_HEALTH_MONITOR=true',
    'FEATURE_SCHEDULER=true',
    'FEATURE_BAL=true',
    'FEATURE_CONNECTORS=true',
    'FEATURE_LOCAL_AGENTIC=true',
    'FEATURE_RISK_TIERED_GOVERNANCE=true',
    'FEATURE_TRUST_LEDGER=true',
    'FEATURE_APPROVAL_LEARNING=true',
    '',
  );

  if (config.commsType && config.commsType !== 'skip') {
    lines.push('# Communications');
    lines.push(`LANCELOT_COMMS_TYPE=${config.commsType}`);

    if (config.commsType === 'telegram') {
      lines.push(`LANCELOT_TELEGRAM_TOKEN=${config.telegramToken}`);
      lines.push(`LANCELOT_TELEGRAM_CHAT_ID=${config.telegramChatId}`);
    } else if (config.commsType === 'google_chat') {
      lines.push(`LANCELOT_CHAT_SPACE_NAME=${config.chatSpaceName}`);
      lines.push('LANCELOT_AUTH_MODE=OAUTH');
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

export async function writeEnvFile(installDir, config) {
  const content = generateEnvContent(config);
  await fs.writeFile(path.join(installDir, '.env'), content, 'utf8');
}

export async function patchDockerCompose(installDir, config) {
  const composePath = path.join(installDir, 'docker-compose.yml');
  let content = await fs.readFile(composePath, 'utf8');
  const lines = content.split('\n');
  const result = [];

  let inGpuBlock = false;
  let gpuIndent = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Replace hardcoded Windows workspace path with relative path
    if (line.includes('Lancelot Workspace:/home/lancelot/workspace')) {
      result.push('      - "./lancelot_workspace:/home/lancelot/workspace"');
      continue;
    }

    // Remove GPU deploy block if no GPU
    if (!config.hasGpu) {
      const trimmed = line.trim();

      // Detect start of deploy: block in local-llm service
      if (trimmed === 'deploy:' && !inGpuBlock) {
        // Check if this looks like the GPU reservation block by peeking ahead
        const nextLines = lines.slice(i + 1, i + 6).join(' ');
        if (nextLines.includes('nvidia') || nextLines.includes('reservations')) {
          inGpuBlock = true;
          gpuIndent = line.search(/\S/);
          continue;
        }
      }

      if (inGpuBlock) {
        const currentIndent = line.search(/\S/);
        // End of block: back to same or lesser indent (or empty line followed by content)
        if (line.trim().length > 0 && currentIndent <= gpuIndent) {
          inGpuBlock = false;
          // Don't skip this line — it's the next section
        } else {
          continue; // Skip GPU block lines
        }
      }
    }

    // Update GPU layers env var to match detected config
    if (line.includes('LOCAL_MODEL_GPU_LAYERS=')) {
      result.push(line.replace(/LOCAL_MODEL_GPU_LAYERS=\d+/, `LOCAL_MODEL_GPU_LAYERS=${config.gpuLayers || 0}`));
      continue;
    }

    result.push(line);
  }

  // Create workspace directory
  const workspaceDir = path.join(installDir, 'lancelot_workspace');
  await fs.mkdir(workspaceDir, { recursive: true });

  // Write patched docker-compose
  await fs.writeFile(composePath, result.join('\n'), 'utf8');
}
