// ============================================================
// Config — .env generation and docker-compose.yml patching
// ============================================================

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { CORE_IMAGE, LOCAL_LLM_CUDA_IMAGE, LOCAL_LLM_IMAGE, PROVIDERS } from './constants.mjs';

function generateToken() {
  return crypto.randomBytes(32).toString('base64url');
}

function generateFernetKey() {
  // Python Fernet requires 44-char base64url WITH padding (=)
  return crypto.randomBytes(32).toString('base64url') + '=';
}

export function generateEnvContent(config) {
  const providerInfo = PROVIDERS[config.provider];
  const warRoomAuthModel = config.warRoomAuthModel || 'local';
  const localLlmImage = config.hasGpu ? LOCAL_LLM_CUDA_IMAGE : LOCAL_LLM_IMAGE;
  const localLlmWheelVariant = config.hasGpu ? 'cu123' : 'cpu';
  const lines = [
    '# ═══════════════════════════════════════════════════════════',
    '# Lancelot Configuration — Generated by create-lancelot',
    `# Generated: ${new Date().toISOString()}`,
    '# ═══════════════════════════════════════════════════════════',
    '',
    '# LLM Provider',
    `LANCELOT_PROVIDER=${config.provider}`,
    'LANCELOT_PROVIDER_MODE=sdk',
  ];

  // OAuth mode: write auth mode instead of API key
  if (config.authMode === 'oauth') {
    lines.push('LANCELOT_AUTH_MODE=OAUTH');
    lines.push(`# ${providerInfo.envVar} not needed — using OAuth`);
  } else {
    lines.push(`${providerInfo.envVar}=${config.apiKey}`);
  }

  // Generate security tokens — store API token in config for OAuth flow
  const ownerToken = generateToken();
  const apiToken = generateToken();
  const hostAgentToken = generateToken();
  const vaultKey = generateFernetKey();
  config._generatedApiToken = apiToken;
  config._generatedHostAgentToken = hostAgentToken;

  lines.push(
    '',
    '# Security Tokens (auto-generated — keep secret)',
    `LANCELOT_OWNER_TOKEN=${ownerToken}`,
    `LANCELOT_API_TOKEN=${apiToken}`,
    `LANCELOT_VAULT_KEY=${vaultKey}`,
    `HOST_AGENT_TOKEN=${hostAgentToken}`,
    '',
    '# War Room Authentication',
    `LANCELOT_AUTH_PROVIDER=${warRoomAuthModel}`,
  );

  if (warRoomAuthModel === 'oidc') {
    lines.push(
      `OIDC_ISSUER_URL=${config.oidcIssuerUrl || ''}`,
      `OIDC_CLIENT_ID=${config.oidcClientId || ''}`,
      `OIDC_CLIENT_SECRET=${config.oidcClientSecret || ''}`,
      `OIDC_REDIRECT_URI=${(config.oidcBaseUrl || 'http://localhost:8000').replace(/\/$/, '')}/auth/oidc/callback`,
      `OIDC_ALLOWED_GROUPS=${config.oidcAllowedGroups || ''}`,
      `OIDC_ALLOW_ANY_AUTHENTICATED=${config.oidcAllowAnyAuthenticated ? 'true' : 'false'}`,
      '',
    );
  } else {
    const warRoomUser = (config.warRoomUser || '').trim();
    if (!warRoomUser) {
      throw new Error('War Room username is required for local authentication');
    }
    const warRoomPassword = config.warRoomPassword || crypto.randomBytes(12).toString('base64url');
    const resetCode = config.warRoomPasswordResetCode || crypto.randomBytes(12).toString('base64url');
    config.warRoomUser = warRoomUser;
    config.warRoomPassword = warRoomPassword;
    config.warRoomPasswordResetCode = resetCode;
    lines.push(
      `WARROOM_USERNAME=${warRoomUser}`,
      `WARROOM_PASSWORD=${warRoomPassword}`,
      `WARROOM_PASSWORD_RESET_CODE=${resetCode}`,
      '',
    );
  }

  lines.push(
    '',
    '# Deployment',
    `LANCELOT_CORE_IMAGE=${CORE_IMAGE}`,
    'LANCELOT_DATA_MOUNT=./lancelot_data',
    'LANCELOT_WORKSPACE_MOUNT=./lancelot_workspace',
    '',
    '# Logging',
    'LANCELOT_LOG_LEVEL=INFO',
    '',
    '# Local Model',
    `LOCAL_LLM_IMAGE=${localLlmImage}`,
    'LOCAL_LLM_PULL_POLICY=missing',
    'LOCAL_LLM_DOCKERFILE=Dockerfile',
    `LOCAL_LLM_WHEEL_VARIANT=${localLlmWheelVariant}`,
    'LOCAL_LLM_WHEEL_VERSION=0.3.19',
    'LOCAL_LLM_HEALTH_START_PERIOD=900s',
    `LOCAL_MODEL_GPU_LAYERS=${config.gpuLayers || 0}`,
    '',
    '# Feature Flags — Core',
    'FEATURE_SOUL=true',
    'FEATURE_SKILLS=true',
    'FEATURE_HEALTH_MONITOR=true',
    'FEATURE_SCHEDULER=true',
    'FEATURE_BAL=true',
    'FEATURE_CONNECTORS=true',
    'FEATURE_AGENTIC_LOOP=true',
    'FEATURE_LOCAL_AGENTIC=true',
    'FEATURE_MEMORY_VNEXT=true',
    'FEATURE_TOOLS_FABRIC=true',
    '',
    '# Feature Flags — Governance',
    'FEATURE_RISK_TIERED_GOVERNANCE=true',
    'FEATURE_TRUST_LEDGER=true',
    'FEATURE_APPROVAL_LEARNING=true',
    'FEATURE_POLICY_CACHE=true',
    'FEATURE_INTENT_TEMPLATES=true',
    'FEATURE_ASYNC_VERIFICATION=true',
    '',
    '# Feature Flags — Intelligence',
    'FEATURE_UNIFIED_CLASSIFICATION=true',
    'FEATURE_CLAIM_VERIFICATION=true',
    'FEATURE_STRUCTURED_OUTPUT=true',
    'FEATURE_TOOL_FLOW_STREAMING=true',
    'FEATURE_ACTION_CARDS=true',
    '',
    '# Feature Flags — Security',
    'FEATURE_SKILL_SECURITY_PIPELINE=true',
    '',
  );

  if (config.commsType === 'skip') {
    lines.push('# Communications');
    lines.push('LANCELOT_COMMS_TYPE=none');
    lines.push('');
  } else if (config.commsType) {
    lines.push('# Communications');
    lines.push(`LANCELOT_COMMS_TYPE=${config.commsType}`);

    if (config.commsType === 'telegram') {
      lines.push(`LANCELOT_TELEGRAM_TOKEN=${config.telegramToken}`);
      lines.push(`LANCELOT_TELEGRAM_CHAT_ID=${config.telegramChatId}`);
    } else if (config.commsType === 'google_chat') {
      lines.push(`LANCELOT_CHAT_SPACE_NAME=${config.chatSpaceName}`);
      lines.push('LANCELOT_AUTH_MODE=OAUTH');
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

export async function writeEnvFile(installDir, config) {
  const content = generateEnvContent(config);
  await fs.writeFile(path.join(installDir, '.env'), content, 'utf8');
}

export async function patchDockerCompose(installDir, config) {
  const composePath = path.join(installDir, 'docker-compose.yml');
  let content = await fs.readFile(composePath, 'utf8');
  const lines = content.split('\n');
  const result = [];

  let inGpuBlock = false;
  let gpuIndent = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Keep installer-created host bootstrap/workspace paths wired into the
    // running container while preserving named-volume defaults for bare compose.
    if (line.includes('lancelot_data:/home/lancelot/data') ||
        line.includes('./lancelot_data:/home/lancelot/data')) {
      result.push('      - ${LANCELOT_DATA_MOUNT:-lancelot_data}:/home/lancelot/data');
      continue;
    }

    if (line.includes('Lancelot Workspace:/home/lancelot/workspace') ||
        line.includes('lancelot_workspace:/home/lancelot/workspace') ||
        line.includes('./lancelot_workspace:/home/lancelot/workspace')) {
      result.push('      - ${LANCELOT_WORKSPACE_MOUNT:-lancelot_workspace}:/home/lancelot/workspace');
      continue;
    }

    // Remove GPU deploy block if no GPU
    if (!config.hasGpu) {
      const trimmed = line.trim();

      // Detect start of deploy: block in local-llm service
      if (trimmed === 'deploy:' && !inGpuBlock) {
        // Check if this looks like the GPU reservation block by peeking ahead
        const nextLines = lines.slice(i + 1, i + 6).join(' ');
        if (nextLines.includes('nvidia') || nextLines.includes('reservations')) {
          inGpuBlock = true;
          gpuIndent = line.search(/\S/);
          continue;
        }
      }

      if (inGpuBlock) {
        const currentIndent = line.search(/\S/);
        // End of block: back to same or lesser indent (or empty line followed by content)
        if (line.trim().length > 0 && currentIndent <= gpuIndent) {
          inGpuBlock = false;
          // Don't skip this line — it's the next section
        } else {
          continue; // Skip GPU block lines
        }
      }
    }

    // Update GPU layers env var to match detected config
    if (line.includes('LOCAL_MODEL_GPU_LAYERS=')) {
      result.push(line.replace(/LOCAL_MODEL_GPU_LAYERS=\d+/, `LOCAL_MODEL_GPU_LAYERS=${config.gpuLayers || 0}`));
      continue;
    }

    result.push(line);
  }

  // Create workspace directory
  const workspaceDir = path.join(installDir, 'lancelot_workspace');
  await fs.mkdir(workspaceDir, { recursive: true });

  // Write patched docker-compose
  await fs.writeFile(composePath, result.join('\n'), 'utf8');
}
