import importlib

import pytest


STRICT_REQUEST_MODELS = [
    ("src.hive.api", "TaskSubmitRequest"),
    ("src.hive.api", "PauseRequest"),
    ("src.hive.api", "KillRequest"),
    ("src.hive.api", "ModifyRequest"),
    ("src.hive.api", "KillAllRequest"),
    ("src.a2a.api", "RegisterAgentRequest"),
    ("src.a2a.api", "DelegateRequest"),
    ("src.a2a.server", "TaskSendRequest"),
    ("src.mcp.api", "RegisterRequest"),
    ("src.mcp.api", "StatusRequest"),
    ("src.mcp.api", "CredentialRequest"),
    ("src.observability.api", "OTelConfigUpdate"),
    ("src.observability.api", "WebhookConfigUpdate"),
    ("src.observability.api", "MetricsApiConfigUpdate"),
    ("src.observability.api", "WebhookEndpointCreate"),
    ("src.connectors.credential_api", "StoreCredentialRequest"),
    ("src.compliance.api", "ExportRequest"),
    ("src.timetravel.api", "InspectRequest"),
    ("src.timetravel.api", "ReplayRequest"),
    ("src.timetravel.api", "ForkRequest"),
    ("src.core.memory.api", "SearchRequest"),
    ("src.core.memory.api", "BeginCommitRequest"),
    ("src.core.memory.api", "AddEditRequest"),
    ("src.core.memory.api", "FinishCommitRequest"),
    ("src.core.memory.api", "RollbackRequest"),
    ("src.core.memory.api", "PromoteRequest"),
    ("src.core.memory.api", "MemoryActionRequest"),
    ("src.core.memory.api", "CompileContextRequest"),
    ("src.incidents.api", "AcknowledgeRequest"),
    ("src.incidents.api", "StatusUpdateRequest"),
    ("src.incidents.api", "TimelineEntryRequest"),
    ("src.incidents.api", "LinkReceiptRequest"),
    ("src.incidents.api", "EscalateRequest"),
    ("src.incidents.api", "CloseRequest"),
    ("src.core.providers.api", "SwitchProviderRequest"),
    ("src.core.providers.api", "LaneOverrideRequest"),
    ("src.core.providers.api", "RotateKeyRequest"),
    ("src.core.actioncard_api", "ResolveRequest"),
    ("src.core.skills_api", "ApproveRequest"),
    ("src.core.skills_api", "RejectRequest"),
    ("src.core.control_plane", "UpdateModelUsagePolicyRequest"),
    ("src.core.control_plane", "RuntimePauseRequest"),
    ("src.core.control_plane", "OnboardingCommandRequest"),
    ("src.core.control_plane", "WarRoomArtifactRequest"),
    ("src.core.control_plane", "TokenRevokeRequest"),
    ("src.core.governance_api", "ApprovalDecisionRequest"),
    ("src.core.trust_api", "ProposalDecisionRequest"),
    ("src.core.apl_api", "RuleDecisionRequest"),
    ("src.core.setup_api", "ConfirmRequest"),
    ("src.core.setup_api", "FactoryResetRequest"),
    ("src.core.auth_api", "LoginRequest"),
    ("src.core.auth_api", "ResetPasswordRequest"),
    ("src.core.auth_api", "OidcExchangeRequest"),
    ("src.core.auth_api", "ChangePasswordRequest"),
    ("src.core.flags_api", "AllowlistUpdate"),
    ("src.core.flags_api", "WriteCommandsUpdate"),
    ("src.federation.api", "UpdateFederationSettingsRequest"),
    ("src.federation.api", "FederationCommandRequest"),
    ("src.federation.api", "PauseSignalRequest"),
    ("src.federation.api", "ResumeSignalRequest"),
    ("src.federation.api", "HandoffInitiationRequest"),
    ("src.federation.api", "SoulConfirmationRequest"),
    ("src.federation.api", "SoulHandshakeRequest"),
    ("src.federation.api", "SoulUpdateRequest"),
    ("src.federation.api", "PeerRegistrationRequest"),
    ("src.federation.api", "PeerConfirmationRequest"),
    ("src.federation.api", "BudgetReportRequest"),
    ("src.federation.api", "ManageRegisterPeerRequest"),
    ("src.federation.api", "ManageHandoffRequest"),
    ("src.federation.api", "ManageCompleteHandoffRequest"),
    ("src.federation.api", "CompletionReportRequest"),
    ("src.federation.api", "ManageKillRequest"),
    ("src.federation.graph_api", "CreateTopologyRequest"),
    ("src.federation.graph_api", "AddNodeRequest"),
    ("src.federation.graph_api", "AddEdgeRequest"),
    ("src.federation.graph_api", "AcknowledgeYellowRequest"),
    ("src.federation.graph_api", "UpdateContractRequest"),
    ("src.core.connectors_api", "BackendSetRequest"),
    ("src.core.scheduler_api", "JobTimezoneRequest"),
    ("src.core.soul.api", "ProposeAmendmentRequest"),
    ("src.core.soul.template_api", "ApplyTemplateRequest"),
]


@pytest.mark.parametrize(("module_name", "class_name"), STRICT_REQUEST_MODELS)
def test_request_models_forbid_extra_fields(module_name, class_name):
    module = importlib.import_module(module_name)
    model_cls = getattr(module, class_name)
    assert model_cls.model_config.get("extra") == "forbid"
