# Lancelot - A Governed Autonomous System
# Copyright (c) 2026 Myles Russell Hamilton
# Licensed under BUSL-1.1. See LICENSE for details.

"""
Auditor handoff bundle helpers.

JSON evidence is necessary, but enterprises generally want a single portable
package that includes a machine-readable artifact, a quick-review summary, and
basic indices/integrity material.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import zipfile
from typing import Any, Dict, List, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title",
            parent=base["Title"],
            fontSize=22,
            leading=28,
            textColor=colors.HexColor("#1a1a2e"),
        ),
        "heading": ParagraphStyle(
            "heading",
            parent=base["Heading2"],
            fontSize=13,
            leading=17,
            textColor=colors.HexColor("#0f3460"),
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["BodyText"],
            fontSize=9,
            leading=13,
        ),
    }


def _table(rows: List[List[str]], widths: List[int]) -> Table:
    table = Table(rows, colWidths=widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d7dbe0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f7f9")]),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def generate_bundle_summary_pdf(
    export_format: str,
    export_data: Dict[str, Any],
) -> bytes:
    """Generate a short summary PDF for bundled JSON exports."""
    meta = export_data.get("export_metadata", {})
    integrity = export_data.get("integrity", {})
    scope = export_data.get("export_scope", {})
    exceptions = export_data.get("exception_summary", {})
    attribution = export_data.get("operator_attribution_summary", {})

    styles = _build_styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        title=f"{export_format} audit summary",
    )

    elements: List[Any] = []
    elements.append(Paragraph(f"{export_format} Audit Bundle", styles["title"]))
    elements.append(Spacer(1, 8))
    elements.append(
        Paragraph(
            "This PDF is a quick-review summary for the bundled evidence package. "
            "The JSON artifact remains the source of detailed machine-readable evidence.",
            styles["body"],
        )
    )
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Export Metadata", styles["heading"]))
    elements.append(
        _table(
            [
                ["Field", "Value"],
                ["Export ID", str(meta.get("export_id", ""))],
                ["Generated At", str(meta.get("generated_at", ""))],
                ["Generated By", str(meta.get("generated_by", {}).get("display_name", ""))],
                ["Period", f"{meta.get('period_start', '')} to {meta.get('period_end', '')}"],
                ["Receipt Count", str(meta.get("receipt_count", 0))],
                ["Chain Integrity", str(meta.get("chain_integrity", ""))],
            ],
            [110, 350],
        )
    )
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Scope and Attribution", styles["heading"]))
    elements.append(
        _table(
            [
                ["Metric", "Value"],
                ["Quest Count", str(scope.get("quest_count", 0))],
                ["Human Actions", str(attribution.get("attribution_counts", {}).get("human", 0))],
                ["Automation Actions", str(attribution.get("attribution_counts", {}).get("automation", 0))],
                ["Federated Peer Actions", str(attribution.get("attribution_counts", {}).get("federated_peer", 0))],
                ["Legacy Unattributed", str(attribution.get("attribution_counts", {}).get("legacy_unattributed", 0))],
                ["Operational Exceptions", str(exceptions.get("total_exception_receipts", 0))],
            ],
            [160, 300],
        )
    )
    elements.append(Spacer(1, 10))

    if export_format == "SOC2_JSON":
        control_summary = export_data.get("control_summary", {})
        elements.append(Paragraph("SOC 2 Control Summary", styles["heading"]))
        elements.append(
            _table(
                [
                    ["Metric", "Value"],
                    ["Total Controls", str(control_summary.get("total_controls", 0))],
                    ["Controls With Evidence", str(control_summary.get("controls_with_evidence", 0))],
                    ["Controls Without Evidence", str(control_summary.get("controls_without_evidence", 0))],
                    ["Controls With Exceptions", str(control_summary.get("controls_with_exceptions", 0))],
                ],
                [180, 280],
            )
        )
    elif export_format == "ISO27001_JSON":
        soa = export_data.get("statement_of_applicability", {})
        elements.append(Paragraph("ISO 27001 Statement of Applicability", styles["heading"]))
        elements.append(
            _table(
                [
                    ["Metric", "Value"],
                    ["Controls In Scope", str(soa.get("controls_in_scope", 0))],
                    ["Controls Out of Scope", str(soa.get("controls_out_of_scope", 0))],
                ],
                [180, 280],
            )
        )
    elif export_format == "GDPR_JSON":
        processing = export_data.get("processing_summary", {})
        elements.append(Paragraph("GDPR Processing Summary", styles["heading"]))
        elements.append(
            _table(
                [
                    ["Metric", "Value"],
                    ["Unique Recipients", str(len(processing.get("unique_recipients", [])))],
                    ["PII Categories Observed", str(len(processing.get("pii_categories_observed", [])))],
                    ["Article 30 Attention Quests", str(processing.get("quests_requiring_article_30_attention", 0))],
                ],
                [180, 280],
            )
        )

    elements.append(Spacer(1, 10))
    elements.append(Paragraph("Integrity Note", styles["heading"]))
    elements.append(
        Paragraph(
            f"Chain status: {integrity.get('chain_status', '')}. "
            "Use the included manifest and the COMPLIANCE_EXPORT_GENERATED receipt to verify bundle integrity.",
            styles["body"],
        )
    )

    doc.build(elements)
    return buf.getvalue()


def generate_bundle_index_csv(
    export_format: str,
    export_data: Dict[str, Any],
) -> bytes:
    """Generate a simple CSV index for auditor or GRC tooling."""
    buf = io.StringIO()
    writer = csv.writer(buf)

    if export_format in {"SOC2_JSON", "ISO27001_JSON"}:
        writer.writerow(
            [
                "control_id",
                "description",
                "control_status",
                "evidence_count",
                "exception_count",
            ]
        )
        for control_id, control in export_data.get("controls", {}).items():
            writer.writerow(
                [
                    control_id,
                    control.get("description", ""),
                    control.get("control_status", ""),
                    control.get("evidence_count", 0),
                    control.get("exception_count", 0),
                ]
            )
    elif export_format == "GDPR_JSON":
        writer.writerow(
            [
                "quest_id",
                "personal_data_processed",
                "pii_event_count",
                "total_actions",
                "recipient_count",
                "period_start",
                "period_end",
            ]
        )
        for record in export_data.get("processing_activities", {}).get("records", []):
            writer.writerow(
                [
                    record.get("quest_id", ""),
                    record.get("personal_data_processed", False),
                    record.get("pii_event_count", 0),
                    record.get("total_actions", 0),
                    len(record.get("recipients", [])),
                    record.get("period_start", ""),
                    record.get("period_end", ""),
                ]
            )

    return buf.getvalue().encode("utf-8")


def build_audit_bundle(
    export_format: str,
    export_data: Dict[str, Any],
    *,
    artifact_basename: str,
) -> Tuple[bytes, Dict[str, Any]]:
    """
    Build a ZIP bundle for JSON compliance exports.

    Returns:
        (bundle_bytes, manifest_dict)
    """
    json_bytes = json.dumps(export_data, indent=2).encode("utf-8")
    summary_pdf = generate_bundle_summary_pdf(export_format, export_data)
    index_csv = generate_bundle_index_csv(export_format, export_data)
    readme = (
        "Lancelot Compliance Audit Bundle\n"
        "\n"
        "Contents:\n"
        "- evidence JSON: machine-readable control or processing evidence\n"
        "- summary PDF: quick-review auditor summary\n"
        "- CSV index: flat control or processing index\n"
        "- manifest JSON: file hashes and bundle metadata\n"
    ).encode("utf-8")

    files = {
        f"{artifact_basename}.json": json_bytes,
        f"{artifact_basename}_summary.pdf": summary_pdf,
        f"{artifact_basename}_index.csv": index_csv,
        "README.txt": readme,
    }

    manifest = {
        "bundle_type": "compliance_audit_bundle",
        "format": export_format,
        "format_version": export_data.get("export_metadata", {}).get("format_version", ""),
        "export_id": export_data.get("export_metadata", {}).get("export_id", ""),
        "files": [
            {
                "name": name,
                "sha256": _sha256(content),
                "size_bytes": len(content),
            }
            for name, content in files.items()
        ],
    }
    manifest_bytes = json.dumps(manifest, indent=2).encode("utf-8")
    files["manifest.json"] = manifest_bytes

    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content in files.items():
            zf.writestr(name, content)

    return out.getvalue(), manifest
