name: Security Vulnerability
description: Report a security vulnerability (USE PRIVATE DISCLOSURE FOR SENSITIVE ISSUES)
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **STOP** - If this vulnerability could be exploited in production, DO NOT file it here.

        Instead, email **security@projectlancelot.com** with details. We will respond within 48 hours.

        This public template is for low-severity security observations, hardening suggestions,
        and security-related feature requests only.

        See [SECURITY.md](../SECURITY.md) for our full responsible disclosure policy.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      options:
        - "Low - hardening suggestion or defense-in-depth improvement"
        - "Medium - potential issue but requires specific conditions"
        - "High - STOP, use private disclosure (security@projectlancelot.com)"
        - "Critical - STOP, use private disclosure (security@projectlancelot.com)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security observation or suggestion.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could go wrong if this is not addressed?

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a fix in mind, describe it here.
